# Generated by Django 5.1.6 on 2025-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('night', 'Night Shift'), ('custom', 'Custom Shift')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='can_work_shifts',
        ),
        migrations.AddField(
            model_name='employee',
            name='available_days',
            field=models.ManyToManyField(blank=True, to='schedule.day'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_work_shifts',
            field=models.ManyToManyField(blank=True, to='schedule.shifttype'),
        ),
    ]
