# Generated by Django 5.1.6 on 2025-02-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_day_shifttype_remove_employee_available_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftrequirement',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shiftrequirement',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shiftrequirement',
            name='shift_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.shifttype'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='end_time',
            field=models.TimeField(default='16:00'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
