# Generated by Django 5.1.6 on 2025-02-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_shiftrequirement_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='priority',
            field=models.IntegerField(default=1, help_text='Niži broj znači viši prioritet'),
        ),
    ]
