# Generated by Django 5.1.6 on 2025-02-06 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_employee_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='required_junior_hca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftrequirement',
            name='required_junior_nurses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftrequirement',
            name='required_senior_hca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftrequirement',
            name='required_senior_nurses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shiftrequirement',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.shifttype'),
        ),
    ]
