# Generated by Django 5.1.6 on 2025-02-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_shiftrequirement_required_junior_hca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.department'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='duration_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
