# Generated by Django 5.1.6 on 2025-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_shiftrequirement_required_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequirement',
            name='required_roles',
            field=models.ManyToManyField(to='schedule.role'),
        ),
    ]
